[input]
url_prefix = "https://qian-gu.github.io"
html_selector = "main"
base_directory = "/home/qian/repositories/qian-gu.github.io/output"

[[input.files]]
path = "pages/about-me.html"
url = "/pages/about-me.html"
title = "About Me"

[[input.files]]
path = "posts/cs/understanding-and-using-c-pointers-notes.html"
url = "/posts/cs/understanding-and-using-c-pointers-notes.html"
title = "深入理解 C 指针读书笔记"

[[input.files]]
path = "posts/risc-v/riscv-book-note.html"
url = "/posts/risc-v/riscv-book-note.html"
title = "RISC-V Book 阅读笔记"

[[input.files]]
path = "posts/tools/iverilog-verilator-and-gtkwave.html"
url = "/posts/tools/iverilog-verilator-and-gtkwave.html"
title = "开源 IC 工具/库 —— iverilog、verilator 和 gtkwave"

[[input.files]]
path = "posts/ic/ca-cache.html"
url = "/posts/ic/ca-cache.html"
title = "Computer Architecture 笔记 —— Cache"

[[input.files]]
path = "posts/tools/fusesoc-summary.html"
url = "/posts/tools/fusesoc-summary.html"
title = "Fusesoc 小结"

[[input.files]]
path = "posts/ic/verilog-and-systemverilog-gotchas-notes.html"
url = "/posts/ic/verilog-and-systemverilog-gotchas-notes.html"
title = "《Verilog and SystemVerilog gotchas》笔记"

[[input.files]]
path = "posts/ic/systemverilog-for-design-notes.html"
url = "/posts/ic/systemverilog-for-design-notes.html"
title = "《SystemVerilog for Design》笔记"

[[input.files]]
path = "posts/risc-v/risc-v-spec-notes-2-privileged.html"
url = "/posts/risc-v/risc-v-spec-notes-2-privileged.html"
title = "RISC-V Spec 阅读笔记 #2 —— Privileged ISA"

[[input.files]]
path = "posts/ic/learning-patterson-and-hennessy-notes-6-chapter-6.html"
url = "/posts/ic/learning-patterson-and-hennessy-notes-6-chapter-6.html"
title = "Patterson and Hennessy 学习笔记 #6 —— Chapter 6 Parallel processors from Client to Cloud"

[[input.files]]
path = "posts/ic/learning-patterson-and-hennessy-notes-5-chapter-5.html"
url = "/posts/ic/learning-patterson-and-hennessy-notes-5-chapter-5.html"
title = "Patterson and Hennessy 学习笔记 #5 —— Chapter 5 Large and Fast:Exploiting Memory Hierarchy"

[[input.files]]
path = "posts/ic/learning-patterson-and-hennessy-notes-4-chapter-4.html"
url = "/posts/ic/learning-patterson-and-hennessy-notes-4-chapter-4.html"
title = "Patterson and Hennessy 学习笔记 #4 —— Chapter 4 The Processor"

[[input.files]]
path = "posts/ic/learning-patterson-and-hennessy-notes-3-chapter-3.html"
url = "/posts/ic/learning-patterson-and-hennessy-notes-3-chapter-3.html"
title = "Patterson and Hennessy 学习笔记 #3 —— Chapter 3 Arithmetic For Computers"

[[input.files]]
path = "posts/ic/learning-patterson-and-hennessy-notes-2-chapter-2.html"
url = "/posts/ic/learning-patterson-and-hennessy-notes-2-chapter-2.html"
title = "Patterson and Hennessy 学习笔记 #2 —— Chapter 2 Instructions: Language of the Computer"

[[input.files]]
path = "posts/ic/learning-patterson-and-hennessy-notes-1-chapter-1.html"
url = "/posts/ic/learning-patterson-and-hennessy-notes-1-chapter-1.html"
title = "Patterson and Hennessy 学习笔记 #1 —— Chapter 1 Computer Abstractions and Technology"

[[input.files]]
path = "posts/risc-v/risc-v-spec-notes-1-unprivileged.html"
url = "/posts/risc-v/risc-v-spec-notes-1-unprivileged.html"
title = "RISC-V Spec 阅读笔记 #1 —— Unprivileged ISA"

[[input.files]]
path = "posts/tools/learning-vim-pratical-vim-notes.html"
url = "/posts/tools/learning-vim-pratical-vim-notes.html"
title = "学习 Vim 之《Pratical Vim》读书笔记"

[[input.files]]
path = "posts/cs/python-notes-10-fp-in-python.html"
url = "/posts/cs/python-notes-10-fp-in-python.html"
title = "Python 学习笔记 #10 —— Python 中的 FP"

[[input.files]]
path = "posts/cs/python-notes-9-function-arguments.html"
url = "/posts/cs/python-notes-9-function-arguments.html"
title = "Python 学习笔记 #9 —— Function Arguments 函数参数"

[[input.files]]
path = "posts/cs/python-notes-8-decorator.html"
url = "/posts/cs/python-notes-8-decorator.html"
title = "Python 学习笔记 #8 —— Decorator 装饰器"

[[input.files]]
path = "posts/cs/python-notes-7-generator.html"
url = "/posts/cs/python-notes-7-generator.html"
title = "Python 学习笔记 #7 —— Generator 生成器"

[[input.files]]
path = "posts/cs/python-notes-6-iterator.html"
url = "/posts/cs/python-notes-6-iterator.html"
title = "Python 学习笔记 #6 —— Iterator 迭代器"

[[input.files]]
path = "posts/tools/git-flow-summary.html"
url = "/posts/tools/git-flow-summary.html"
title = "Git Flow 小结"

[[input.files]]
path = "posts/cs/python-notes-5-comprehension.html"
url = "/posts/cs/python-notes-5-comprehension.html"
title = "Python 学习笔记 #5 —— Comprehension 解析式"

[[input.files]]
path = "posts/cs/python-notes-4-the-zen-of-python.html"
url = "/posts/cs/python-notes-4-the-zen-of-python.html"
title = "Python 学习笔记 #4 —— Python 之禅"

[[input.files]]
path = "posts/cs/python-notes-3-docstring-style.html"
url = "/posts/cs/python-notes-3-docstring-style.html"
title = "Python 学习笔记 #3 —— Docstring 风格"

[[input.files]]
path = "posts/cs/python-notes-2-pep8-in-practice.html"
url = "/posts/cs/python-notes-2-pep8-in-practice.html"
title = "Python 学习笔记 #2 —— PEP8 实践"

[[input.files]]
path = "posts/cs/python-notes-1-pep8-style.html"
url = "/posts/cs/python-notes-1-pep8-style.html"
title = "Python 学习笔记 #1 —— PEP8 编程风格"

[[input.files]]
path = "posts/cs/python-notes-0-summary.html"
url = "/posts/cs/python-notes-0-summary.html"
title = "Python 学习笔记 #0 —— 新的开始"

[[input.files]]
path = "posts/ic/fifo-design-notes.html"
url = "/posts/ic/fifo-design-notes.html"
title = "FIFO 设计笔记"

[[input.files]]
path = "posts/telecom/summary-of-frequency-in-digital-signal-processing.html"
url = "/posts/telecom/summary-of-frequency-in-digital-signal-processing.html"
title = "数字信号处理中的各种频率"

[[input.files]]
path = "posts/ic/low-power-design.html"
url = "/posts/ic/low-power-design.html"
title = "低功耗设计"

[[input.files]]
path = "posts/ic/the-art-of-pipelining.html"
url = "/posts/ic/the-art-of-pipelining.html"
title = "流水线 pipeline 的艺术"

[[input.files]]
path = "posts/tools/learning-vim-signature-plugin.html"
url = "/posts/tools/learning-vim-signature-plugin.html"
title = "学习 Vim 之 vim-signature 插件"

[[input.files]]
path = "posts/cs/summary-of-regular-expression.html"
url = "/posts/cs/summary-of-regular-expression.html"
title = "Regular Expression 小结"

[[input.files]]
path = "posts/ic/verilog-hdl-coding-style-guide.html"
url = "/posts/ic/verilog-hdl-coding-style-guide.html"
title = "Verilog HDL coding style"

[[input.files]]
path = "posts/ic/clock-generate-unit.html"
url = "/posts/ic/clock-generate-unit.html"
title = "时钟生成"

[[input.files]]
path = "posts/ic/configurable-design.html"
url = "/posts/ic/configurable-design.html"
title = "可配置设计"

[[input.files]]
path = "posts/ic/summary-of-case-in-verilog.html"
url = "/posts/ic/summary-of-case-in-verilog.html"
title = "Verilog 的 case 小结"

[[input.files]]
path = "posts/book/on-top-of-tides-review.html"
url = "/posts/book/on-top-of-tides-review.html"
title = "不想当司机的厨子不是好码农 —— 读《浪潮之巅》"

[[input.files]]
path = "posts/ic/static-timing-analysis-2-xilinx-sta.html"
url = "/posts/ic/static-timing-analysis-2-xilinx-sta.html"
title = "静态时序分析 STA 2 —— Xilinx STA"

[[input.files]]
path = "posts/ic/static-timing-analysis-1-basic.html"
url = "/posts/ic/static-timing-analysis-1-basic.html"
title = "静态时序分析 STA 1 —— 基础知识"

[[input.files]]
path = "posts/telecom/correlation-coefficient-and-matlab-function.html"
url = "/posts/telecom/correlation-coefficient-and-matlab-function.html"
title = "相关系数及Matlab函数"

[[input.files]]
path = "posts/ic/summary-of-hazard-and-glitch.html"
url = "/posts/ic/summary-of-hazard-and-glitch.html"
title = "关于冒险和毛刺"

[[input.files]]
path = "posts/telecom/ifft-and-fft-in-ofdm.html"
url = "/posts/telecom/ifft-and-fft-in-ofdm.html"
title = "OFDM 中的 IFFT/FFT 注意事项"

[[input.files]]
path = "posts/telecom/summary-of-snr-and-noise.html"
url = "/posts/telecom/summary-of-snr-and-noise.html"
title = "信噪比小结"

[[input.files]]
path = "posts/tools/learning-vim-bufexplorer-nerdtree-winmanager-airline.html"
url = "/posts/tools/learning-vim-bufexplorer-nerdtree-winmanager-airline.html"
title = "学习 Vim 之 BufExplorer、NERDTree、WinManager、Airline 插件"

[[input.files]]
path = "posts/tools/learning-vim-markdown.html"
url = "/posts/tools/learning-vim-markdown.html"
title = "在 Vim 中写 Markdown 文件"

[[input.files]]
path = "posts/tools/learning-vim-ctags-gutentags-cscope-taglist.html"
url = "/posts/tools/learning-vim-ctags-gutentags-cscope-taglist.html"
title = "学习 Vim 之 Ctags/Gutentags/Cscope/Taglist"

[[input.files]]
path = "posts/ic/doxygen-for-verilog.html"
url = "/posts/ic/doxygen-for-verilog.html"
title = "针对 Verilog 的 Doxygen"

[[input.files]]
path = "posts/ic/drawing-fsm-state-diagram-using-graphviz.html"
url = "/posts/ic/drawing-fsm-state-diagram-using-graphviz.html"
title = "利用 Graphviz 画 FSM 状态图"

[[input.files]]
path = "posts/tools/doxygen-cpp-comment-style.html"
url = "/posts/tools/doxygen-cpp-comment-style.html"
title = "基于 Doxygen 的 C++ 注释风格"

[[input.files]]
path = "posts/tools/learning-vim-doxygentoolkit.html"
url = "/posts/tools/learning-vim-doxygentoolkit.html"
title = "学习 Vim 插件 DoxygenToolKit.vim"

[[input.files]]
path = "posts/tools/how-to-analyse-code-elegantly.html"
url = "/posts/tools/how-to-analyse-code-elegantly.html"
title = "如何优雅的分析代码"

[[input.files]]
path = "posts/telecom/tail-bitting-convolutional-code-implementation-in-matlab-and-c-and-fpga.html"
url = "/posts/telecom/tail-bitting-convolutional-code-implementation-in-matlab-and-c-and-fpga.html"
title = "LTE 咬尾卷积编码器的 Matlab 、C 语言及 FPGA 实现"

[[input.files]]
path = "posts/ic/delay-in-fpgas.html"
url = "/posts/ic/delay-in-fpgas.html"
title = "FPGA 中的延时"

[[input.files]]
path = "posts/ic/counter-design-summary.html"
url = "/posts/ic/counter-design-summary.html"
title = "计数器设计小结"

[[input.files]]
path = "posts/book/the-pomodoro-technique-practices.html"
url = "/posts/book/the-pomodoro-technique-practices.html"
title = "番茄工作法 总结 + 实践"

[[input.files]]
path = "posts/book/getting-things-done-review.html"
url = "/posts/book/getting-things-done-review.html"
title = "GTD 书评 + 总结"

[[input.files]]
path = "posts/ic/clock-dividers.html"
url = "/posts/ic/clock-dividers.html"
title = "时钟分频器"

[[input.files]]
path = "posts/ic/the-clock-design-in-fpga-3-multiasynchronous-clock-design.html"
url = "/posts/ic/the-clock-design-in-fpga-3-multiasynchronous-clock-design.html"
title = "FPGA 时钟设计 3 —— 跨时钟域设计"

[[input.files]]
path = "posts/ic/latch-versus-flip-flop.html"
url = "/posts/ic/latch-versus-flip-flop.html"
title = "锁存器 Latch v.s. 触发器 Flip-Flop"

[[input.files]]
path = "posts/ic/vhdl-notes-2-system-design.html"
url = "/posts/ic/vhdl-notes-2-system-design.html"
title = "VHDL 笔记 2 —— 系统设计"

[[input.files]]
path = "posts/ic/vhdl-notes-1-circuit-design.html"
url = "/posts/ic/vhdl-notes-1-circuit-design.html"
title = "VHDL 笔记 1 —— 电路设计"

[[input.files]]
path = "posts/ic/the-clock-design-in-fpga-2-clock-design.html"
url = "/posts/ic/the-clock-design-in-fpga-2-clock-design.html"
title = "FPGA 时钟设计 2 —— 时钟设计"

[[input.files]]
path = "posts/telecom/digital-signal-processing-and-matlab.html"
url = "/posts/telecom/digital-signal-processing-and-matlab.html"
title = "数字信号处理和相关matlab函数总结"

[[input.files]]
path = "posts/ic/xilinx-fft-core-notes.html"
url = "/posts/ic/xilinx-fft-core-notes.html"
title = "Xilinx FFT IP core 笔记"

[[input.files]]
path = "posts/ic/the-clock-design-in-fpga-1-summary-of-clock-resource.html"
url = "/posts/ic/the-clock-design-in-fpga-1-summary-of-clock-resource.html"
title = "FPGA 时钟设计 1 —— 时钟资源总结"

[[input.files]]
path = "posts/ic/parameterization-modeling-in-veriog.html"
url = "/posts/ic/parameterization-modeling-in-veriog.html"
title = "Verilog 中的参数化建模"

[[input.files]]
path = "posts/ic/fpga-digital-processing-basic-2.html"
url = "/posts/ic/fpga-digital-processing-basic-2.html"
title = "FPGA 数字处理基础 (2)"

[[input.files]]
path = "posts/tools/extend-verilog-snippet-in-st2.html"
url = "/posts/tools/extend-verilog-snippet-in-st2.html"
title = "扩展 ST2 Verilog 插件的 snippet"

[[input.files]]
path = "posts/ic/the-art-of-reset-design-in-fpga.html"
url = "/posts/ic/the-art-of-reset-design-in-fpga.html"
title = "FPGA 中的复位设计"

[[input.files]]
path = "posts/embedded/learn-arduino-series-3-intel-galileo-linux.html"
url = "/posts/embedded/learn-arduino-series-3-intel-galileo-linux.html"
title = "学习 Arduino #3 Intel Galileo Linux"

[[input.files]]
path = "posts/ic/fsm-design.html"
url = "/posts/ic/fsm-design.html"
title = "有限状态机 FSM 设计"

[[input.files]]
path = "posts/embedded/learn-arduino-series-2-intel-galileo-development-board.html"
url = "/posts/embedded/learn-arduino-series-2-intel-galileo-development-board.html"
title = "学习 Arduino #2 初识 Intel Galileo 开发板"

[[input.files]]
path = "posts/embedded/learn-arduino-series-1-getting-started.html"
url = "/posts/embedded/learn-arduino-series-1-getting-started.html"
title = "学习 Arduino #1 Arduino 入门"

[[input.files]]
path = "posts/ic/fpga-digital-processing-basic-1.html"
url = "/posts/ic/fpga-digital-processing-basic-1.html"
title = "FPGA 数字处理基础 (1)"

[[input.files]]
path = "posts/telecom/learning-ofdm-on-fpga-1-ofdm-basic.html"
url = "/posts/telecom/learning-ofdm-on-fpga-1-ofdm-basic.html"
title = "学习 OFDM 及其 FPGA 实现 1 —— OFDM Basic"

[[input.files]]
path = "posts/misc/my-pkm.html"
url = "/posts/misc/my-pkm.html"
title = "我的 PKM"

[[input.files]]
path = "posts/cs/learning-linux-package-management.html"
url = "/posts/cs/learning-linux-package-management.html"
title = "学习 Linux 软件包依赖管理"

[[input.files]]
path = "posts/tools/learning-vim-save-project-configuration.html"
url = "/posts/tools/learning-vim-save-project-configuration.html"
title = "学习 Vim 保存项目设置"

[[input.files]]
path = "posts/tools/learning-vim-vundle.html"
url = "/posts/tools/learning-vim-vundle.html"
title = "学习 Vim 使用 Vundle 管理插件"

[[input.files]]
path = "posts/tools/learning-vim-vimrc-preliminary.html"
url = "/posts/tools/learning-vim-vimrc-preliminary.html"
title = "学习 Vim 初步配置 Vim"

[[input.files]]
path = "posts/cs/cosnt-qualifier.html"
url = "/posts/cs/cosnt-qualifier.html"
title = "C++ const 限定符"

[[input.files]]
path = "posts/tools/learning-linux-ssh.html"
url = "/posts/tools/learning-linux-ssh.html"
title = "学习 Linux SSH"

[[input.files]]
path = "posts/ic/learning-fpga-getting-started.html"
url = "/posts/ic/learning-fpga-getting-started.html"
title = "学习 FPGA 入门"

[[input.files]]
path = "posts/cs/built-in-types.html"
url = "/posts/cs/built-in-types.html"
title = "C/C++ 内置数据类型"

[[input.files]]
path = "posts/tools/learning-vim-survival.html"
url = "/posts/tools/learning-vim-survival.html"
title = "学习 Vim 存活"

[[input.files]]
path = "posts/book/code-review.html"
url = "/posts/book/code-review.html"
title = "Code 书评"

[[input.files]]
path = "posts/cs/signed-number-representations.html"
url = "/posts/cs/signed-number-representations.html"
title = "原码、反码、补码"
